Ref: Refactor tests to return 0 if they succeed

diff --git a/etcd-conf/etcd-conf b/etcd-conf/etcd-conf
--- a/etcd-conf/etcd-conf
+++ b/etcd-conf/etcd-conf
@@ -83,7 +83,7 @@ if [[ -n "$ETCD_EXISTING_PEER_URLS" && "$ETCD_EXISTING_PEER_NAMES" != *"$AWS_INS
   for i in $MISSING_PEERS; do
     echo "${APP}: Removing bad peer ${i}"
     status=$($CURL -w %{http_code} "${ETCD_GOOD_MEMBER_URL}/v2/members/${i}" -XDELETE)
-    [[ $status != '204' ]] && echo "${APP}: ERROR - failed to remove bad peer: $i" && exit 1
+    [[ $status == '204' ]] || { echo "${APP}: ERROR - failed to remove bad peer: $i"; exit 1 }
   done
 
   # Get current good peers after cleanup
@@ -93,7 +93,7 @@ if [[ -n "$ETCD_EXISTING_PEER_URLS" && "$ETCD_EXISTING_PEER_NAMES" != *"$AWS_INS
   # Joining existing cluster 
   echo "${APP}: Adding instance to existing cluster"
   status=$($CURL -w %{http_code} -o /dev/null -XPOST "$ETCD_GOOD_MEMBER_URL/v2/members" -H "Content-Type: application/json" -d "{\"peerURLs\": [\"${ETCD_PROTO}://${AWS_IP}:${ETCD_PEER_PORT}\"], \"name\": \"${AWS_INSTANCE_ID}\"}")
-  [[ $status != '204' && $status != '409' ]] && echo "${APP}: ERROR - unable to add instance to exisitng cluster" && exit 1
+  [[ $status == '204' || $status == '409' ]] || { echo "${APP}: ERROR - unable to add instance to exisitng cluster"; exit 1 }
 
   ETCD_INITIAL_CLUSTER_STATE='existing'
 
diff --git a/flannel-conf/flannel-conf b/flannel-conf/flannel-conf
--- a/flannel-conf/flannel-conf
+++ b/flannel-conf/flannel-conf
@@ -37,8 +37,8 @@ CURL="/usr/bin/curl ${CURL_OPTS}"
 echo "${APP}: Downloading certificates"
 for i in $CERTIFICATES; do
   echo "${APP}: ${i}"
-  [[ -f "${FLANNEL_PATH}/$i" ]] | (/usr/bin/aws s3api get-object --bucket "${K8S_S3_BUCKET}" --key "${i}" "${FLANNEL_PATH}/${i}")
-  [[ ! -f "${FLANNEL_PATH}/$i" ]] && echo "${APP}: Error - failed to download ${i} certificate" && exit 1
+  [[ -f "${FLANNEL_PATH}/$i" ]] || (/usr/bin/aws s3api get-object --bucket "${K8S_S3_BUCKET}" --key "${i}" "${FLANNEL_PATH}/${i}")
+  [[ -f "${FLANNEL_PATH}/$i" ]] || { echo "${APP}: Error - failed to download ${i} certificate"; exit 1 }
 done
 
 # Get AWS AZ
@@ -131,12 +131,12 @@ else
   # Disable source-dest check for the instance
   echo "${APP}: Disabling source-destination check for the instance"
   $AWS ec2 modify-instance-attribute --instance-id "${AWS_INSTANCE_ID}" --source-dest-check "{\"Value\": false}"
-  [[ $? -ne 0 ]] && echo "${APP}: Error - failed to disable source-destination check for the instance" && exit 1
+  [[ $? -eq 0 ]] || { echo "${APP}: Error - failed to disable source-destination check for the instance"; exit 1 }
 
   # Add iptables nat to be able to talk to outside the overlay network world
   echo "${APP}: Configuring iptables"
   $IPTABLES_CMD -w -t nat -A POSTROUTING -o eth0 -j MASQUERADE \! -d "${FLANNEL_NETWORK}"
-  [[ $? -ne 0 ]] && echo "${APP}: Error - failed to configure iptables" && exit 1
+  [[ $? -eq 0 ]] || { echo "${APP}: Error - failed to configure iptables"; exit 1 }
 
   cat << EOF > $FLANNEL_ENV_FILE
 FLANNELD_REMOTE=${FLANNEL_REMOTE}
diff --git a/kube-labels/kube-labels b/kube-labels/kube-labels
--- a/kube-labels/kube-labels
+++ b/kube-labels/kube-labels
@@ -5,29 +5,33 @@ K8S_MASTER=${K8S_MASTER:?'$K8S_MASTER is not set'}
 K8S_POD=${K8S_POD:?'$K8S_POD is not set'}
 K8S_ROLE=${K8S_ROLE:?'$K8S_ROLE is not set'}
 
-CURL_CONNECT_TIMEOUT=30
+CURL_OPTS=${CURL_OPTS:-'-s -f --connect-timeout 30'}
+CURL="/usr/bin/curl ${CURL_OPTS}"
 
 echo "${APP}: Pod ${K8S_POD}"
 
 # Get AWS AZ
-AWS_AZ=$(curl -s --connect-timeout ${CURL_CONNECT_TIMEOUT} 'http://169.254.169.254/latest/meta-data/placement/availability-zone')
-[[ -z "${AWS_AZ}" ]] && echo "${APP}: Error - failed to get aws ec2 region" && exit 1
-echo "${APP}: Found aws region - ${AWS_AZ}"
+AWS_AZ=$($CURL 'http://169.254.169.254/latest/meta-data/placement/availability-zone')
+AWS_REGION=${AWS_AZ%%[a-z]}
+AWS_REGION=${AWS_REGION:?"${APP}: Error - failed to get aws ec2 region"}
+echo "${APP}: Found aws region - ${AWS_REGION}"
 
-INSTANCE_ID=$(curl -s --connect-timeout ${CURL_CONNECT_TIMEOUT} 'http://169.254.169.254/latest/meta-data/instance-id')
-[[ -z "${INSTANCE_ID}" ]] && echo "${APP}: Error - failed to get aws instance-id" && exit 1
-echo "${APP}: Found aws instance-id - ${INSTANCE_ID}"
+# Get Instance ID
+AWS_INSTANCE_ID=$($CURL 'http://169.254.169.254/latest/meta-data/instance-id')
+AWS_INSTANCE_ID=${AWS_INSTANCE_ID:?"${APP}: Error - failed to get aws instance-id"}
+echo "${APP}: Found aws instance-id - ${AWS_INSTANCE_ID}"
 
-INSTANCE_TYPE=$(curl -s --connect-timeout ${CURL_CONNECT_TIMEOUT} 'http://169.254.169.254/latest/meta-data/instance-type')
-[[ -z "${INSTANCE_TYPE}" ]] && echo "${APP}: Error - failed to get aws instance-type" && exit 1
-echo "${APP}: Found aws instance-type - ${INSTANCE_TYPE}"
+# Get Instance Type
+AWS_INSTANCE_TYPE=$($CURL 'http://169.254.169.254/latest/meta-data/instance-type')
+AWS_INSTANCE_TYPE=${AWS_INSTANCE_TYPE:?"${APP}: Error - failed to get aws instance-type"}
+echo "${APP}: Found aws instance-id - ${AWS_INSTANCE_TYPE}"
 
 # Wait for API server and get Node name
 attempt=1
 while [[ -z "$NODE" ]] || [[ "$NODE" == "null" ]]; do
   echo "${APP}: Retrieving host name, attempt ${attempt}"
   sleep 2
-  NODE=$(curl -s --connect-timeout ${CURL_CONNECT_TIMEOUT} -f --cert /srv/kubernetes/client.pem --key /srv/kubernetes/client-key.pem --cacert /srv/kubernetes/ca.pem  \
+  NODE=$($CURL --cert /srv/kubernetes/client.pem --key /srv/kubernetes/client-key.pem --cacert /srv/kubernetes/ca.pem  \
          ${K8S_MASTER}/api/v1/namespaces/kube-system/pods/${K8S_POD} | jq -r '.spec.nodeName'
        )
   attempt=$(($attempt+1))
@@ -44,18 +48,19 @@ for i in $@; do
 done
 
 echo "${APP}: Updating node labels"
-curl -s --cert /srv/kubernetes/client.pem --key /srv/kubernetes/client-key.pem --cacert /srv/kubernetes/ca.pem  \
+$CURL --cert /srv/kubernetes/client.pem --key /srv/kubernetes/client-key.pem --cacert /srv/kubernetes/ca.pem  \
      --request PATCH -H "Content-Type: application/strategic-merge-patch+json" \
      -d @- "${K8S_MASTER}/api/v1/nodes/${NODE}" <<EOF
 {
   "metadata": {
     "labels": {
-${TEST}      "kubernetes.io/aws-id":   "${INSTANCE_ID}",
-      "kubernetes.io/aws-type": "${INSTANCE_TYPE}",
-      "kubernetes.io/aws-az":   "${AWS_AZ}",
-      "kubernetes.io/role":   "${K8S_ROLE}"
+      "kubernetes.io/aws-id":     "${AWS_INSTANCE_ID}",
+      "kubernetes.io/aws-type":   "${AWS_INSTANCE_TYPE}",
+      "kubernetes.io/aws-az":     "${AWS_AZ}",
+      "kubernetes.io/aws-region": "${AWS_REGION}",
+      "kubernetes.io/role":       "${K8S_ROLE}"
     }
   }
 }
 EOF
-[[ $? -ne 0 ]] && echo "${APP}: Error - failed to update node labels" && exit 1
+[[ "$?" -eq 0 ]] || { echo "${APP}: Error - failed to update node labels"; exit 1 }
